//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 07:14:22 PM EET 
//


package bg.government.regixclient.responses.mvr.bds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.government.regixclient.responses.mvr.bds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonalIdentityInfoResponse_QNAME = new QName("http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse", "PersonalIdentityInfoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.government.regixclient.responses.mvr.bds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonalIdentityInfoResponse }
     * 
     */
    public PersonalIdentityInfoResponse createPersonalIdentityInfoResponseType() {
        return new PersonalIdentityInfoResponse();
    }

    /**
     * Create an instance of {@link PersonNames }
     * 
     */
    public PersonNames createPersonNames() {
        return new PersonNames();
    }

    /**
     * Create an instance of {@link ReturnInformation }
     * 
     */
    public ReturnInformation createReturnInformation() {
        return new ReturnInformation();
    }

    /**
     * Create an instance of {@link BirthPlace }
     * 
     */
    public BirthPlace createBirthPlace() {
        return new BirthPlace();
    }

    /**
     * Create an instance of {@link PermanentAddress }
     * 
     */
    public PermanentAddress createPermanentAddress() {
        return new PermanentAddress();
    }

    /**
     * Create an instance of {@link NationalityList }
     * 
     */
    public NationalityList createNationalityList() {
        return new NationalityList();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalIdentityInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse", name = "PersonalIdentityInfoResponse")
    public JAXBElement<PersonalIdentityInfoResponse> createPersonalIdentityInfoResponse(PersonalIdentityInfoResponse value) {
        return new JAXBElement<PersonalIdentityInfoResponse>(_PersonalIdentityInfoResponse_QNAME, PersonalIdentityInfoResponse.class, null, value);
    }

}
