//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 07:14:22 PM EET 
//


package bg.government.regixclient.responses.mvr.bds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ����� �� ������� �� ���� �� �������� �� �����������
 * 
 * <p>Java class for PersonalIdentityInfoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalIdentityInfoResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReturnInformations" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}ReturnInformation" minOccurs="0"/>
 *         &lt;element name="EGN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonNames" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}PersonNames" minOccurs="0"/>
 *         &lt;element name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DocumentTypeLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IdentityDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IssuerPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssuerPlaceLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssuerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssuerNameLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="BirthPlace" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}BirthPlace" minOccurs="0"/>
 *         &lt;element name="GenderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GenderNameLatin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NationalityList" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}NationalityList" minOccurs="0"/>
 *         &lt;element name="PermanentAddress" type="{http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoResponse}PermanentAddress" minOccurs="0"/>
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="EyesColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="IdentitySignature" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalIdentityInfoResponse", propOrder = {
    "returnInformations",
    "egn",
    "personNames",
    "documentType",
    "documentTypeLatin",
    "identityDocumentNumber",
    "issueDate",
    "issuerPlace",
    "issuerPlaceLatin",
    "issuerName",
    "issuerNameLatin",
    "validDate",
    "birthDate",
    "birthPlace",
    "genderName",
    "genderNameLatin",
    "nationalityList",
    "permanentAddress",
    "height",
    "eyesColor",
    "picture",
    "identitySignature"
})
public class PersonalIdentityInfoResponse {

    @XmlElement(name = "ReturnInformations")
    protected ReturnInformation returnInformations;
    @XmlElement(name = "EGN")
    protected String egn;
    @XmlElement(name = "PersonNames")
    protected PersonNames personNames;
    @XmlElement(name = "DocumentType")
    protected String documentType;
    @XmlElement(name = "DocumentTypeLatin")
    protected String documentTypeLatin;
    @XmlElement(name = "IdentityDocumentNumber")
    protected String identityDocumentNumber;
    @XmlElement(name = "IssueDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueDate;
    @XmlElement(name = "IssuerPlace")
    protected String issuerPlace;
    @XmlElement(name = "IssuerPlaceLatin")
    protected String issuerPlaceLatin;
    @XmlElement(name = "IssuerName")
    protected String issuerName;
    @XmlElement(name = "IssuerNameLatin")
    protected String issuerNameLatin;
    @XmlElement(name = "ValidDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validDate;
    @XmlElement(name = "BirthDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "BirthPlace")
    protected BirthPlace birthPlace;
    @XmlElement(name = "GenderName")
    protected String genderName;
    @XmlElement(name = "GenderNameLatin")
    protected String genderNameLatin;
    @XmlElement(name = "NationalityList")
    protected NationalityList nationalityList;
    @XmlElement(name = "PermanentAddress")
    protected PermanentAddress permanentAddress;
    @XmlElement(name = "Height")
    protected Double height;
    @XmlElement(name = "EyesColor")
    protected String eyesColor;
    @XmlElement(name = "Picture")
    protected byte[] picture;
    @XmlElement(name = "IdentitySignature")
    protected byte[] identitySignature;

    /**
     * Gets the value of the returnInformations property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnInformation }
     *     
     */
    public ReturnInformation getReturnInformations() {
        return returnInformations;
    }

    /**
     * Sets the value of the returnInformations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnInformation }
     *     
     */
    public void setReturnInformations(ReturnInformation value) {
        this.returnInformations = value;
    }

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

    /**
     * Gets the value of the personNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNames }
     *     
     */
    public PersonNames getPersonNames() {
        return personNames;
    }

    /**
     * Sets the value of the personNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNames }
     *     
     */
    public void setPersonNames(PersonNames value) {
        this.personNames = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentTypeLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentTypeLatin() {
        return documentTypeLatin;
    }

    /**
     * Sets the value of the documentTypeLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentTypeLatin(String value) {
        this.documentTypeLatin = value;
    }

    /**
     * Gets the value of the identityDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityDocumentNumber() {
        return identityDocumentNumber;
    }

    /**
     * Sets the value of the identityDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityDocumentNumber(String value) {
        this.identityDocumentNumber = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issuerPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerPlace() {
        return issuerPlace;
    }

    /**
     * Sets the value of the issuerPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerPlace(String value) {
        this.issuerPlace = value;
    }

    /**
     * Gets the value of the issuerPlaceLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerPlaceLatin() {
        return issuerPlaceLatin;
    }

    /**
     * Sets the value of the issuerPlaceLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerPlaceLatin(String value) {
        this.issuerPlaceLatin = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerName(String value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the issuerNameLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerNameLatin() {
        return issuerNameLatin;
    }

    /**
     * Sets the value of the issuerNameLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerNameLatin(String value) {
        this.issuerNameLatin = value;
    }

    /**
     * Gets the value of the validDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidDate() {
        return validDate;
    }

    /**
     * Sets the value of the validDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidDate(XMLGregorianCalendar value) {
        this.validDate = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link BirthPlace }
     *     
     */
    public BirthPlace getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthPlace }
     *     
     */
    public void setBirthPlace(BirthPlace value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the genderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderName() {
        return genderName;
    }

    /**
     * Sets the value of the genderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderName(String value) {
        this.genderName = value;
    }

    /**
     * Gets the value of the genderNameLatin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderNameLatin() {
        return genderNameLatin;
    }

    /**
     * Sets the value of the genderNameLatin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderNameLatin(String value) {
        this.genderNameLatin = value;
    }

    /**
     * Gets the value of the nationalityList property.
     * 
     * @return
     *     possible object is
     *     {@link NationalityList }
     *     
     */
    public NationalityList getNationalityList() {
        return nationalityList;
    }

    /**
     * Sets the value of the nationalityList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalityList }
     *     
     */
    public void setNationalityList(NationalityList value) {
        this.nationalityList = value;
    }

    /**
     * Gets the value of the permanentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PermanentAddress }
     *     
     */
    public PermanentAddress getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * Sets the value of the permanentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermanentAddress }
     *     
     */
    public void setPermanentAddress(PermanentAddress value) {
        this.permanentAddress = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the eyesColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEyesColor() {
        return eyesColor;
    }

    /**
     * Sets the value of the eyesColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEyesColor(String value) {
        this.eyesColor = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPicture(byte[] value) {
        this.picture = value;
    }

    /**
     * Gets the value of the identitySignature property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getIdentitySignature() {
        return identitySignature;
    }

    /**
     * Sets the value of the identitySignature property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setIdentitySignature(byte[] value) {
        this.identitySignature = value;
    }

}
