//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 07:13:56 PM EET 
//


package bg.government.regixclient.requests.mvr.bds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.government.regixclient.requests.mvr.bds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonalIdentityInfoRequest_QNAME = new QName("http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest", "PersonalIdentityInfoRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.government.regixclient.requests.mvr.bds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonalIdentityInfoRequest }
     * 
     */
    public PersonalIdentityInfoRequest createPersonalIdentityInfoRequestType() {
        return new PersonalIdentityInfoRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalIdentityInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest", name = "PersonalIdentityInfoRequest")
    public JAXBElement<PersonalIdentityInfoRequest> createPersonalIdentityInfoRequest(PersonalIdentityInfoRequest value) {
        return new JAXBElement<PersonalIdentityInfoRequest>(_PersonalIdentityInfoRequest_QNAME, PersonalIdentityInfoRequest.class, null, value);
    }

}
